fix Composer dependencies require a PHP version ">= 8.5.0"
Fatal error: Uncaught RuntimeException: Composer detected issues in your
platform: Your Composer dependencies require a PHP version ">= 8.5.0".
You are running 8.3.32.

composer why-not php 8.3.32